siteb/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.post_home, name="home" ),
	url(r'^create/$', views.post_create, name="create"),
	url(r'^detail/(?P<pk>\d+)/$', views.post_detail, name="detail" ),
	url(r'^list/$', views.post_list, name="list" ),
	url(r'^(?P<pk>\d+)/edit/$', views.post_update, name="update" ),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name="delete"),

]

siteb/siteb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import login_view, logout_view, register_view

urlpatterns = [
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^login/', login_view,name="login"),
    url(r'^logout/', logout_view,name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^admin/', admin.site.urls),
    url(r'^', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteb/posts/models.py
from django.conf import settings
from django.utils import timezone
from django.db import models
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from django.urls import reverse 
from comments.models import Comment
from posts.utils import get_read_time
from django.contrib.contenttypes.models import ContentType


#class PostManager(models.Manager):
	#def all(self,*args,**kwargs):
		#return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())

#here we set our won location for saving of image
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)
# Create your models here.
class Post(models.Model):

	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	
	title = models.CharField(max_length=120)
	#slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field = "width_field", height_field ="height_field")
	height_field = models.IntegerField(default=100)
	width_field = models.IntegerField(default=100)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateTimeField(auto_now=False,auto_now_add=False)
	read_time = models.IntegerField(default=0)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)

	#objects = PostManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"pk":self.id})
		#return "/posts/%s" %(self.id)

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

	def read_time_fxn(self):
		if self.content:
			html_string = self.get_markdown()
			read_time_var = get_read_time(html_string)
			self.read_time = read_time_var

	class Meta:
		ordering = ["-timestamp","-updated"]

	@property
	def comments(self):
		instance=self
		qs=Comment.objects.filter_by_instance(instance)
		return qs

	@property
	def get_content_type(self):
		instance=self		
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

siteb/posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget


class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"height_field",
			"width_field",
			"draft",
			"publish",
			
		]

siteb/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Post
from .forms import PostForm
from comments.models import Comment
from django.db.models import Q
from django.contrib import messages
from urllib.parse import quote_plus
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from comments.forms import CommentForm
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse


# Create your views here.
def post_home(request):
	return render(request,"base.html", {})

def post_create(request):
	if request.user.is_authenticated():
		form = PostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			messages.success(request, "successfully created")
			return HttpResponseRedirect(instance.get_absolute_url())
		
		context = {
			"form":form,
		}	
		return render(request,"post_form.html", context)
	else:
		messages.success(request, "<b>You must login to create any post</b>", extra_tags='html_safe')
		return HttpResponseRedirect(reverse('posts:list'))


def post_detail(request, pk=None):
	instance = get_object_or_404(Post, id=pk)
	share_string = quote_plus(instance.content)
	#Post.objects.get(id=instance.id)
	initial_data = {
		"content_type" : instance.get_content_type,
		"object_id" : instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type=form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get("object_id")
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = int(request.POST.get("parent_id"))
		except:
			parent_id = None
		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() ==1:
				parent_obj = parent_qs.first()

		new_comment, created = Comment.objects.get_or_create(
				user=request.user,
				content_type=content_type,
				object_id=obj_id,
				content=content_data,
				parent=parent_obj
			)
		messages.success(request, "commment successfully posted")
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


	comments = instance.comments
	context={
		"title":"Post Detail",
		"instance" : instance,
		"share_string" : share_string,
		"comments" : comments,
		"comment_form" : form,
	}
	return render(request,"post_detail.html", context)

def post_list(request): 
	queryset_list = Post.objects.all()#.order_by("-timestamp")
	
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(Q(title__icontains=query)|Q(content__icontains=query)|Q(user__first_name__icontains=query)|Q(user__last_name__icontains=query)).distinct()
	#here a new this pagination applied to list view
	paginator = Paginator(queryset_list, 10) # Show 25 contacts per page
	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"title":"List",
		"object_list":queryset
	}
	return render(request,"post_list.html", context)
	#return HttpResponse("<h1>list</h1>")
def post_update(request, pk=None):
	"""here we can take instance.auth name and check directly"""#sorted

	instance = get_object_or_404(Post, id=pk)
	if request.user == instance.user or request.user.is_superuser:
		form = PostForm(request.POST or None, request.FILES or None, instance=instance)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request, "<a href='#'>Item</a>Saved", extra_tags='html_safe')
			return HttpResponseRedirect(instance.get_absolute_url())

		context={
			"title":instance.title,
			"instance" : instance,
			"form":form,
		}
		return render(request,"post_form.html", context)
	else:
		messages.success(request, "<b>You are not the author of post</b>", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	


def post_delete(request,pk=None):
	
	instance = get_object_or_404(Post, id=pk)
	if request.user == instance.user or request.user.is_superuser:
		instance.delete()
		messages.success(request, "successfully deleted")
		return redirect("posts:list")
	else:
		messages.success(request, "<b>You are not the author of post</b>", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

siteb/templates/base.html
 
<html>
<head>

<title>{% block head_title %}BLoG{% endblock head_title %}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!--
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "posts:home" %}">BLoG</a>
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url "posts:list" %}">List Post<span class="sr-only">(current)</span></a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url "posts:create" %}">Create</a></li>
      </ul>
    </div>
  </div>
</nav>-->
{% load static %}
<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>

{% block head_extra %}{% endblock head_extra  %}

</head>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

{% include "messages_display.html" %}
<div class='container'>
  <ol class='breadcrumb'>
        <li><a href='{% url "posts:list" %}'>Home</a></li>
        {% block post_detail_link %}
        {% endblock %}

        {% if not request.user.is_authenticated %}
        <li class='pull-right'><a href='{% url "register" %}'>Register</a></li>
        <li class='pull-right'><a href='{% url "login" %}'>Login</a></li>
        {% else %}
        <li><a href='{% url "posts:create" %}'>Create Post</a></li>
        <li class='pull-right'><a href='{% url "logout" %}'>Logout</a></li>
        {% endif %}
</ol>
{% block content%}

{% endblock content %}
</div>


<script
        src="http://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous">
</script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
  $(".content-markdown").each(function(){
    var content = $(this).text()
    var markedContent = marked(content)
    $(this).html(markedContent)
  })
  
  $(".post-detail-item img").each(function(){
    $(this).addClass("img-responsive");
  })

  var contentInput = $("#id_content");
  
  function setContent(value){
    var markedContent = marked(value)
    $("#preview_content").html(markedContent)
    $("#preview_content img").each(function(){
      $(this).addClass("img-responsive")
    })
  }
  setContent(contentInput.val())
  
  contentInput.keyup(function(){
    var newContent = $(this).val()
    setContent(newContent) 
  }) 

  var titleInput = $("#id_title");
  
  function setTitle(value){
    $("#preview_title").text(value)
  }
  setTitle(titleInput.val())
  
  titleInput.keyup(function(){
    var newContent = $(this).val()
    setTitle(newContent) 
  }) 

  $(".comment-reply-btn").click(function(event){
    event.preventDefault();
    $(this).parent().next(".comment-reply").fadeToggle();

  })


})
</script>

</body>

</html>

siteb/templates/comment_thread.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }}|{{block.super }}
{% endblock head_title %}



{% block content %}

<div class="col-sm-6 col-sm-offset-3">
		
	  	<p>{{ comment.content }}</p>
	  	<footer>via {{ comment.user}} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}{% endif %} {% if request.user == comment.user %} | <a href='{{ comment.get_delete_url }}'>Delete</a> {% endif %}</footer>
	  	<hr/>
	  	<div>
		  	{% for child_comment in comment.children %}
		  	<blockquote>
		  	<p>{{ child_comment.content }}</p>
		  	<footer>via {{ child_comment.user}} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'>Delete</a> {% endif %}</footer>
		    </blockquote>
		    {% endfor %}
		  	{% if request.user.is_authenticated %}
		  	<form method="POST" action="">{% csrf_token %}
				{{ form | crispy }}
				<input type='hidden' name='parent_id' value='{{ comment.id }}'>
				<input type='submit' value='Reply' class='btn btn_default'>
			</form>
			{% else %}
			<p>You must login to make a comment</p>
			{% endif %}	
		</div>

		<hr/>

</div>

{% endblock content %}

siteb/templates/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }}|{{block.super }}
{% endblock head_title %}



{% block content %}

<div class="col-sm-6 col-sm-offset-3">
	<h1>Confirm Delete</h1>
		
		  	<form method="POST" action="">{% csrf_token %}
				<p>Are you sure you want to delete:"{{ object.content }}"?</p>
				<input type='submit' value='Confirm' class='btn btn-warning'>
				<a href="{{ object.get_absolute_url }}" class='btn btn-default'>Cancel</a>
			</form>
</div>

{% endblock content %}

siteb/templates/login_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
{{form.media}}
{% endblock head_extra  %}

{% block content%}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>
<form method='POST' action="" enctype='multipart/form-data'>
{% csrf_token %}
{{ form | crispy }}
<input type="submit" class="btn btn-default" value="{{ title }}" > 
</form>
</div>
{% endblock content%}

siteb/templates/messages_display.html
{% if messages %}
	<div class='messages'>
		<ul class='messages'>
			{% for message in messages %}
			<li{% if message.tags %} class="{{message.tags}}"{% endif%}>{% if "html_safe" in message.tags%}{{message|safe}}{% else %}{{ message }}{% endif %}</li>
			{% endfor %}
		</ul>
	</div>
{% endif %}

siteb/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }}|{{block.super }}
{% endblock head_title %}

{% block post_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{% endblock %}



{% block content %}
<a href='{% url "posts:delete" instance.id %}'>
<button type="button" class="btn btn-default" aria-label="Left Align">
  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
</button>
</a>

<div class="col-sm-6 col-sm-offset-3">
	{% if instance.image %}
	<img src="{{ instance.image.url }}" class='img-responsive'>
	{% endif %}
	<h1><u>{{ instance.title }}</u> | <small>{{ instance.timestamp }}</small></h1>
	<br/>
	<p>Read time:{% if instance.read_time <= 1 %} less than 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %}</p>

	{% if instance.user.get_full_name %}
	<p>Author : {{ instance.user.get_full_name }}</p>
	{% else %}
	<p>Author: {{instance.user.username}}
	{% endif %}

	
	<!--<p>
	<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
	Facebook
	</a>
	<a href="https://twitter.com/home?status={{share_string}}%20{{ request.build_absolute_uri }}">
	Twitter</a>
	<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google+</a>
	</p> -->
	<div class='col-sm-12'>
	<div class='thumbnail'>
	<div class='post-detail-item'>{{ instance.get_markdown }}</div>
	</div>
	<br/>
	<hr/>
	<p>
	<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
	</p>
	<br/>
	<div >
		<p class='lead'>Comments</p>
		<hr/>
		{% if request.user.is_authenticated %}
		<form method="POST" action="">{% csrf_token %}
			{{ comment_form | crispy }}
			<input type='submit' value='Post Comment' class='btn btn_default'>
		</form>
		{% else %}
		<p>You must login to make a comment</p>
		{% endif %}
		<hr/>
		{% for comment in comments %}
		<blockquote>
	  	<p>{{ comment.content }}</p>
	  	<footer>via {{ comment.user}} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %}<a class="comment-reply-btn" href="#">Reply</a> | <a class="" href="{{ comment.get_absolute_url }}">Thread</a></footer>
	  	<div class='comment-reply'>
		  	{% for child_comment in comment.children %}
		  	<blockquote>
		  	<p>{{ child_comment.content }}</p>
		  	<footer>via {{ child_comment.user}} | {{ child_comment.timestamp|timesince }} ago</footer>
		    </blockquote>
		    {% endfor %}
		  	
		  	<form method="POST" action="">{% csrf_token %}
				{{ comment_form | crispy }}
				<input type='hidden' name='parent_id' value='{{ comment.id }}'>
				<input type='submit' value='Reply' class='btn btn_default'>
			</form>
		</div>


		</blockquote>
		<hr/>

		{% endfor %}
		
	</div>
	</div>

</div>

{% endblock content %}

siteb/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
{{form.media}}
{% endblock head_extra  %}

{% block content%}
<div class='col-sm-6'>
	<h1>Preview</h1>
	<hr/>
	<div class ='content-preview'>
		<h3 id='preview_title'></h3>
		<p id='preview_content'></p>
	</div>
</div>
<div class='col-sm-6'>
<h1>Fill Post Details</h1>
<hr/>
<form method='POST' action="" enctype='multipart/form-data'>
{% csrf_token %}
{{ form|crispy }}
<input type="submit" value="create" > 
</form>
</div>
{% endblock content%}

siteb/templates/post_list.html
{% extends "base.html" %}
{% block content%}

<div class='col-sm-6 col-sm-offset-3'>
	<h1> {{ title}}</h1>
<form method='GET' action=''>
<input type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
<input type='submit' value='Search'/>
</form>
{% for obj in object_list %}
<div class="row">
	<div class="col-sm-12">
        <div class="thumbnail">
        <div class="caption post-detail-item">
            <h3><a href="{{obj.get_absolute_url}}">{{obj.title}}</a><small> | {{ obj.timestamp|timesince }} ago </small></h3>
            {% if obj.user.get_full_name %}
            <p>Author: {{ obj.user.get_full_name }}</p>
            {% else %}
            <p>Author: {{obj.user.username}}
            {% endif %}
            {% if obj.image %}
            <div class="thumbnail">
                <img src="{{ obj.image.url }}" class='img-responsive' />               
            </div>
            {% endif %}
            {{ obj.get_markdown|truncatechars_html:40 }}
            <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>
        </div>
    </div>
    </div>
</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>
{% endblock content %}